version: '3'

services:
  api:
    restart: always
    build: ./api
    ports:
      - "7000:7000"
    command: gunicorn -w 1 -b :7000 app:app
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api