version: '3'

services:

  api:
    restart: always
    build: ./api
    ports:
      - "8000:8000"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api